name: slimsocial_for_facebook
description: Webview to securely navigate Facebook
publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 10.1.0+113

environment:
  sdk: ">=2.19.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_jailbreak_detection: 1.10.0
  webview_flutter: 4.9.0
  flutter_custom_tabs: 1.0.4
  url_launcher: 6.1.10
  permission_handler: 11.3.1
  shared_preferences: 2.3.2
  app_links: 6.3.2
  settings_ui: 2.0.2
  flutter_riverpod: 2.5.1
  in_app_purchase: 3.2.0
  fluttertoast: 8.2.8
  easy_localization: 3.0.7
  package_info_plus: 8.0.2
  restart_app: 1.3.2
  google_fonts: 6.2.1
  in_app_review: 2.0.9
  share_plus: 10.0.2
  file_picker: 8.1.2
  flutter_file_downloader: 2.0.0
  open_file_plus: 3.4.1
  native_flutter_proxy: 0.1.15

dev_dependencies:
  flutter_launcher_icons: 0.13.1
  custom_lint: 0.6.5
  very_good_analysis: 6.0.0

  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  #android: "launcher_icon"
  ios: true
  android: true
  remove_alpha_ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/lang/
